log:
  level: info

plugins:
  - tag: forward_google
    type: forward
    args:
      upstreams:
        - "https://8.8.8.8/dns-query"

  - tag: udp
    type: udp_server
    args:
      entry: forward_google
      listen: "0.0.0.0:5354"

  - tag: tcp
    type: tcp_server
    args:
      entry: forward_google
      listen: "0.0.0.0:5354"
